// This is the default iconset used by Once UI
import { IconType } from 'react-icons';

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiOutlineArrowPath,
  HiOutlineSun,
  HiOutlineMoon,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineClipboard,
  HiOutlineMagnifyingGlass,
  HiOutlineLink,
  HiArrowUpRight,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiOutlineComputerDesktop,
  HiOutlineQuestionMarkCircle,
  HiOutlineInformationCircle,
  HiOutlineExclamationTriangle,
  HiOutlineExclamationCircle,
  HiOutlineCheckCircle,
  HiOutlineXMark,
  HiOutlineUser,
  HiOutlineEyeDropper,
  HiOutlineMinus,
  HiOutlinePlus,
  HiOutlineCalendar,
  HiOutlineDocumentDuplicate,
  HiOutlineCheck,
  HiOutlineArrowsPointingIn,
  HiOutlineArrowsPointingOut,
  HiOutlineHome,
  HiOutlineDocument,
  HiOutlineCommandLine,
  HiOutlineRocketLaunch,
  HiOutlineUsers,
  HiOutlineHeart,
  HiOutlineChatBubbleBottomCenterText,
  HiOutlineEnvelope,
  HiOutlineArrowDownTray,
  HiOutlineCog6Tooth,
  HiOutlineBars3,
  HiOutlinePaperAirplane,
  HiOutlineGlobeAmericas,
  HiOutlineLightBulb,
  HiOutlineChartBar,
  HiOutlineBolt,
  HiOutlineTrophy,
  HiOutlineViewfinderCircle,
  HiOutlineMapPin,
  HiOutlineBuildingOffice2,
  HiOutlineClock,
  HiOutlineCloud,
  HiOutlineServerStack,
  HiOutlineDocumentText,
  HiOutlinePaintBrush,
  HiOutlineTrash,
} from 'react-icons/hi2';

export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  light: HiOutlineSun,
  dark: HiOutlineMoon,
  help: HiOutlineQuestionMarkCircle,
  info: HiOutlineInformationCircle,
  warning: HiOutlineExclamationTriangle,
  danger: HiOutlineExclamationCircle,
  checkbox: HiOutlineCheck,
  check: HiOutlineCheckCircle,
  copy: HiOutlineDocumentDuplicate,
  eyeDropper: HiOutlineEyeDropper,
  clipboard: HiOutlineClipboard,
  person: HiOutlineUser,
  close: HiOutlineXMark,
  openLink: HiOutlineLink,
  arrowUpRight: HiArrowUpRight,
  minus: HiOutlineMinus,
  plus: HiOutlinePlus,
  calendar: HiOutlineCalendar,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  search: HiOutlineMagnifyingGlass,
  security: HiOutlineShieldCheck,
  sparkle: HiOutlineSparkles,
  computer: HiOutlineComputerDesktop,
  minimize: HiOutlineArrowsPointingIn,
  maximize: HiOutlineArrowsPointingOut,
  home: HiOutlineHome,
  document: HiOutlineDocument,
  command: HiOutlineCommandLine,

  // Additional icons for HELiiX
  rocket: HiOutlineRocketLaunch,
  users: HiOutlineUsers,
  user: HiOutlineUser,
  like: HiOutlineHeart,
  chat: HiOutlineChatBubbleBottomCenterText,
  pages: HiOutlineDocument,
  email: HiOutlineEnvelope,
  download: HiOutlineArrowDownTray,
  settings: HiOutlineCog6Tooth,
  menu: HiOutlineBars3,
  send: HiOutlinePaperAirplane,
  globe: HiOutlineGlobeAmericas,
  brain: HiOutlineLightBulb,
  chartBar: HiOutlineChartBar,
  zap: HiOutlineBolt,
  trophy: HiOutlineTrophy,
  target: HiOutlineViewfinderCircle,
  mapPin: HiOutlineMapPin,
  building2: HiOutlineBuildingOffice2,
  clock: HiOutlineClock,
  cloud: HiOutlineCloud,
  database: HiOutlineServerStack,
  fileText: HiOutlineDocumentText,
  palette: HiOutlinePaintBrush,
  trash: HiOutlineTrash,

  // Semantic mappings for migration
  magic: HiOutlineSparkles,
  shield: HiOutlineShieldCheck,
  activity: HiOutlineChartBar,
  bell: HiOutlineInformationCircle,
  share2: HiOutlineChatBubbleBottomCenterText,
  tv: HiOutlineComputerDesktop,
  plane: HiOutlinePaperAirplane,
  externalLink: HiArrowUpRight,
  heart: HiOutlineHeart,
  messageSquare: HiOutlineChatBubbleBottomCenterText,
  mail: HiOutlineEnvelope,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
